services:
  - type: web
    name: ytfx
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    disk:
      name: ytfx-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /data/ytfx.db
      - key: YOUTUBE_COOKIES
        sync: false
      - key: STATS_TOKEN
        sync: false
